In [1]:
import re
import pandas as pd
from random import choice

from ruwordnet import RuWordNet

from pymystem3 import Mystem

from pymorphy3 import MorphAnalyzer

from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('ru_cefr_short.csv')
df

,fragment,textbook-assigned cefr level
0,"Весной, летом и осенью почти каждую субботу он...",1
1,"Все говорят, что мама хорошая хозяйка. А ещё н...",1
2,На каждой двери красные плакаты и красные фона...,1
3,"Я считаю деньги, в час обедаю в кафе, а потом ...",1
4,Магазин «Чёрный квадрат» открывается в 9 часов...,1
...,...,...
7317,Утечка мозгов стала ключевым трендом междунаро...,6
7318,"По оценкам менеджеров «Промы», такая ситуация ...",6
7319,"Но это не мы, а техно-мемы заполоняют мир благ...",6
7320,Mapillary использует программное обеспечение д...,6
7321,"Новое роботакси, разрабатываемое Маском, сможе...",6

In [3]:
train_texts, val_texts, train_labels, val_labels = train_test_split(
    df['fragment'].values,
    df['textbook-assigned cefr level'].values,
    test_size=0.2,
    random_state=42,
    stratify=df['textbook-assigned cefr level']
)

len(train_texts)

5857

In [4]:
texts_to_augment = []

for i in range(len(train_labels)):
  if train_labels[i] == 6:
    texts_to_augment.append(train_texts[i])


len(texts_to_augment)

120

In [5]:
def tokenize(text):
    return re.findall(r"\w+|[^\w\s]", text, flags=re.UNICODE)

def detokenize(tokens):
    text = ""
    for i, tok in enumerate(tokens):
        if i == 0:
            text += tok
            continue

        if tok in ",.!?:;)]}»":
            text += tok
        elif tokens[i - 1] in "([«":
            text += tok
        else:
            text += " " + tok
    return text

In [6]:
m = Mystem()

def lemmatize(text):
  lemmas = m.lemmatize(text)
    
  lemmas = [i for i in lemmas if i != ' ' and i != '\n']

  return lemmas

In [7]:
morph = MorphAnalyzer()

GOOD_POS = {
    "NOUN",   
    "ADJF", 
    "ADJS",
    "VERB",   
    "INFN"   
}

def is_replaceable_word(word):
    parses = morph.parse(word)
    if not parses:
        return False

    p = parses[0]
    pos = p.tag.POS

    if pos not in GOOD_POS:
        return False

    # исключаем местоимения и местоименные слова
    if pos == "NPRO":
        return False

    # исключаем местоименное прилагательное: этот, мой, какой, всякий
    if "Apro" in p.tag:
        return False

    return True

In [8]:
morph = MorphAnalyzer()

wn = RuWordNet("/home/tyumen/baseline_libs/myenv/lib/python3.12/site-packages/ruwordnet/static/ruwordnet-2021.db")

clean_title = lambda title: re.sub(r'\s*\([^)]*\)', '', title).strip()

def get_synonyms(word):
    parse = morph.parse(word)[0]
    lemma = parse.normal_form
    
    synonyms = []
    
    for sense in wn.get_senses(lemma):
        for synonym_name in sense.synset.senses:
            synonym = synonym_name.name
            synonym = synonym.lower()
            if " " not in synonym and synonym != lemma:
                synonyms.append(clean_title(synonym))
    return synonyms

In [9]:
with open('new_vocab_a1.txt', 'r'):
    file = open('new_vocab_a1.txt')
    a1 = file.readlines()

with open('new_vocab_a2.txt', 'r'):
    file = open('new_vocab_a2.txt')
    a2 = file.readlines()

with open('new_vocab_b1.txt', 'r'):
    file = open('new_vocab_b1.txt')
    b1 = file.readlines()

with open('new_vocab_b2.txt', 'r'):
    file = open('new_vocab_b2.txt')
    b2 = file.readlines()

with open('new_vocab_c1.txt', 'r'):
    file = open('new_vocab_c1.txt')
    c1 = file.readlines()


a1 = set([w.replace('\ufeff', '').strip() for w in a1 if w.strip()])
a2 = set([w.replace('\ufeff', '').strip() for w in a2 if w.strip()])
b1 = set([w.replace('\ufeff', '').strip() for w in b1 if w.strip()])
b2 = set([w.replace('\ufeff', '').strip() for w in b2 if w.strip()])
c1 = set([w.replace('\ufeff', '').strip() for w in c1 if w.strip()])

print(len(a1), len(a2),len(b1), len(b2), len(c1))


only_a1 = a1
only_a2 = a2 - a1
only_b1 = b1 - a2 - a1
only_b2 = b2 - b1 - a2 - a1
only_c1 = c1 - b2 - b1 - a2 - a1

print(len(only_a1), len(only_a2), len(only_b1), len(only_b2), len(only_c1))

923 1493 2821 5867 11961
923 580 1334 3142 6441

In [10]:
def rank_synonyms(synonyms):
    c1 = []
    b2 = []
    b1 = []
    a2 = []
    a1 = []
    
    for synonym in synonyms:
        if synonym in only_c1:
            c1.append(synonym)
        elif synonym in only_b2:
            b2.append(synonym)
        elif synonym in only_b1:
            b1.append(synonym)
        elif synonym in only_a2:
            a2.append(synonym)
        elif synonym in only_a1:
            a1.append(synonym)

    ranked_synonyms = c1 + b2 + b1+ a2+ a1
    return ranked_synonyms

In [11]:
INFLECTABLE_GRAMMEMES = {
    # число
    "sing", "plur",

    # род
    "masc", "femn", "neut",

    # падеж
    "nomn", "gent", "datv", "accs", "ablt", "loct",
    "gen1", "gen2", "acc2", "loc1", "loc2", "voct",

    # одуш/неодуш
    "anim", "inan",

    # глагольные категории
    "past", "pres", "futr",
    "1per", "2per", "3per",
    "indc", "impr",

    # вид
    "perf", "impf",

    # для кратких/полных прилагательных и т.п.
    "Supr", "COMP"
}

def preserve_case(source, target):
    if source.isupper():
        return target.upper()
    if source[0].isupper():
        return target.capitalize()
    return target

def inflect_synonym_like(source_word, ranked_synonyms):
    source_parses = morph.parse(source_word)
    if not source_parses:
        return None
    source_parse = source_parses[0]

    for synonym_lemma in ranked_synonyms:
        synonym_parses = morph.parse(synonym_lemma)
        if  synonym_parses:
            source_pos = source_parse.tag.POS
        
            synonym_parse = None
            for p in synonym_parses:
                if p.tag.POS == source_pos:
                    synonym_parse = p
                    break
        
            if synonym_parse is None:
                synonym_parse = synonym_parses[0]
        
            source_grammemes = set(source_parse.tag.grammemes)
            needed_grammemes = source_grammemes & INFLECTABLE_GRAMMEMES
        
            inflected = synonym_parse.inflect(needed_grammemes)

            if inflected:
                return preserve_case(source_word, inflected.word)
        

    return None

In [15]:
augmented_texts = []
texts = []

LIST_WORDS_TO_REPLACE = []
LEN_WORDS_TO_REPLACE = []
SYNONYMS_COUNT = []
FOUNDED_SYNONYMS = []
RANKED_SYNONYMS = []
CHANGED_SYNONYM = []

for text in texts_to_augment:
    tokens = tokenize(text)
    words_to_replace = {}

    for idx, word in enumerate(tokens):
        if is_replaceable_word(tokens[idx]):
            words_to_replace[idx] = word

    LEN_WORDS_TO_REPLACE.append(len(words_to_replace))
    LIST_WORDS_TO_REPLACE.append(words_to_replace.values())

    words_to_synonyms = {}

    to_print = {}

    syn_count =  []
    founded_syn = []
    ranked_syn = []
    changed_syn = []
    
    for key in words_to_replace.keys():
        synonyms = get_synonyms(tokens[key])
        ranked_synonyms = rank_synonyms(synonyms)

        syn_count.append(len(synonyms))
        founded_syn.append(synonyms)
        ranked_syn.append(ranked_synonyms)

        if len(ranked_synonyms) > 0:
            new_form = inflect_synonym_like(words_to_replace[key], ranked_synonyms)
            if new_form:
                words_to_synonyms[key] = new_form
                changed_syn.append(new_form)
            else:
                changed_syn.append('')

    SYNONYMS_COUNT.append(syn_count)
    FOUNDED_SYNONYMS.append(founded_syn)
    RANKED_SYNONYMS.append(ranked_syn)
    CHANGED_SYNONYM.append(changed_syn)
            
    new_text = []

    for i in range(len(tokens)):
        if i in words_to_synonyms.keys():
            new_text.append(words_to_synonyms[i])
        else:
            new_text.append(tokens[i])

    new_text = detokenize(new_text)

    if new_text != text:
        print(text)
        print(new_text)
        print('\n')

        augmented_texts.append(new_text)
        texts.append(text)

3:38–3:54 Собственно, сама по себе радиация незаразна. Например, мощными дозами излучения от тех же самых изотопов часто стерилизуют фрукты и овощи, а также лечат людей.
3: 38 – 3: 54 Собственно, сама по себе радиация незаразна. Например, могучими дозами излучения от тех же самых изотопов часто стерилизуют фрукты и овощи, а также лечат индивидов.


Недавно компания Uber объявила об инвестиции одного миллиарда долларов в собственную систему автоматизированного вождения, а компания Waymo даже запустила приложение на Android для владельцев их самоуправляемых машин.
Недавно фирма Uber объявила об инвестиции одного миллиарда долларов в собственную привычку автоматизированного вождения, а фирма Waymo даже запустила приложение на Android для собственников их самоуправляемых техник.


Множество повестей: «Двойник», «Дядюшкин сон», «Записки из подполья» и другие, рассказы, публицистика, дневники, даже стихи были в творчестве великого автора.
Множество повестей: «Двойник», «Дядюшкин сон», «Записки из подполья» и другие, рассказы, публицистика, дневники, даже стихи пребывали в творчестве выдающегося автора.


Встречи одноклассников и одногруппников превращаются в вечеринки понтов, одни рвутся туда – доложить о своей крутизне, другие прячутся на илистом дне – нечем козырнуть. Жить мнением других.
Встречи одноклассников и одногруппников преображаются в пирушки понтов, одни разрываются туда – доносить о своей круче, другие скрываются на илистом дне – нечем похвастать. Обитать мнением других.


Самопрезентация — как главная черта времени и наша неизлечимая болезнь. Люди хотят отражаться удачливыми в глазах друг друга. Они презентуют миру своё благополучие. Самопрезентация, хоть слово дико, порабощает всех подряд.
Самопрезентация — как основная грань времени и наша неисправимая патология. Индивиды желают отзываться удачливыми в глазках кореш кореша. Они подарят ладу своё благосостояние. Самопрезентация, хоть высказывание дико, порабощает всех подряд.


Откровенность перед собой – это, наверное, умение прятать в сердце горечь, беречь и накапливать опыты и образы, которые никогда никому не передашь.
Искренность перед собой – это, наверное, умение скрывать в сердце горечь, оберегать и копить эксперименты и облики, которые никогда никому не дашь.


«Сразу после несчастного случая я вспомнил про видео с какими-то невероятными протезами — ловкими, красивыми, управляемыми силой мысли.»
«Сразу после несчастливого эпизода я вспомнил про видео с какими - то немыслимыми протезами — ловкими, моральными, послушными силой думы.»


Я не хочу думать о своей инвалидности, но это не значит, что я избегаю разговоров о ней.
Я не желаю тревожиться о своей инвалидности, но это не значит, что я сторонюсь разговоров о ней.


Ведь несмотря на множество программ, олимпиад и рекламы, увы, до сих пор для многих детей инвалиды подобны инопланетным существам!
Ведь несмотря на множество программ, олимпиад и рекламы, увы, до сих пор для многих детей инвалиды сходные инопланетным существам!


Директор Института социального анализа и прогнозирования РАНХиГС Татьяна Малева объясняет, что в мире сегодня действительно обострилась конкуренция за человеческий капитал, это основной ресурс и мотор развития.
Директор Института общественного анализа и прогнозирования РАНХиГС Татьяна Малева поясняет, что в ладе сегодня действительно обострилась конкуренция за человечный капитал, это главный ресурс и двигатель развития.


Почему мы ещё долго не увидим самоуправляемые машины на дорогах? Новости о достижениях автомобильной промышленности и открытия в сфере искусственного интеллекта создают впечатление, что автоуправляемые машины вот-вот появятся на дорогах.
Почему мы ещё долго не разглядим самоуправляемые техники на трассах? Новинки о достижениях автомобильной индустрии и открытия в арене поддельного разума созидают впечатление, что автоуправляемые техники вот - вот начнутся на трассах.


0:25–1:24 Большинство людей при этом слове впадает в панику, но на самом деле, мы окружены радиацией со всех сторон. Её излучают небо, земля, дома, другие люди и даже бананы!
0: 25 – 1: 24 Большинство индивидов при этом высказывании западает в панику, но на самом занятии, мы окружены радиацией со всех линий. Её сверкают небо, почва, дома, другие индивиды и даже бананы!


Эти изображения люди снимают на смартфоны. В отличие от Street View от Google, который совершенствуется каждые пару лет, карты на платформе Mapillary обновляются каждый день.
Эти изображения индивиды раздевают на смартфоны. В отличие от Street View от Google, который совершенствуется каждые пару годиков, карточки на программе Mapillary обновляют каждый день.


Вообще многие факты из жизни великого классика так или иначе описаны в его произведениях. Например, страсть Достоевского к рулетке легла в основу романа «Игрок».
Вообще многие факты из жизни выдающегося классика так или иначе описаны в его произведениях. Например, страсть Достоевского к рулетке улеглась в суть романа «Игрок».


Богатеть, жрать, гулять, жениться на молодой и красивой – лишь бы другие оценили. И даже притворяться богатым, здоровым и весёлым. Наконец, нагреть руки на мнимостях.
Обогащаться, кушать, прогуливаться, пожениться на молодой и моральной – лишь бы другие оценили. И даже корчить обильным, колоссальным и весёлым. Наконец, кинуть ручки на мнимостях.


Иногда эти частицы-пули сталкиваются с атомами с такой силой, что выбивают из них электроны. Вот почему радиация называется «ионизирующее излучение».
Иногда эти частицы - пули натыкаются с атомами с такой силой, что вырывают из них электроны. Вот почему радиация представляется «ионизирующее излучение».


Но технические, нормативные и этические препятствия всё ещё мешают их распространению. Почему мы ещё не готовы к беспилотникам? В апреле 2019 года Илон Маск анонсировал создание роботакси Tesla.
Но технические, нормативные и этические препятствия всё ещё смешивают их распространению. Почему мы ещё не готовы к беспилотникам? В апреле 2019 годика Илон Маск анонсировал создание роботакси Tesla.


Исследователи пока только мечтают о будущем, в котором самоуправляемые автомобили смогут быть не только потребителями, но и производителями данных о дороге, снимая изображения улиц во время движения.
Исследователи пока только мечтают о будущем, в котором самоуправляемые автомобили сумеют пребывать не только потребителями, но и производителями данных о трассе, снимая изображения улиц во время сообщения.


Утечка мозгов стала ключевым трендом международной миграции последних лет, уверены западные эксперты. На днях ВОИС обнародовала исследование, подтверждающее эту тенденцию и к тому же содержащее парадоксальные открытия.
Утечка мозгов стала ключевым трендом межгосударственной миграции конечных годиков, уверены западные специалисты. На днях ВОИС обнародовала изучение, подтверждающее эту линию и к тому же содержащее парадоксальные открытия.


Как измерить мем и как зафиксировать факт его самовоспроизведения, передачи и распространения? Как правильно описать мем и определить его содержание? Вторая проблема связана с определением мема.
Как померить мем и как фиксировать факт его самовоспроизведения, дачи и распространения? Как правильно рассказать мем и задать его основание? Вторая заморочка связана с определением мема.


«Человек без тайности – пустая грамота» – есть такая пословица. Между тем скоростной ритм требует не только лаконичности и цепляющей броскости суждений, но и их частоты.
«Индивид без тайности – бессодержательная грамота» – пребывать такая пословица. Между тем скоростной такт требуется не только лаконичности и цепляющей броскости мнений, но и их частоты.


Ведь в будущем новым приёмам придётся научиться не только самоуправляемым машинам, но и нам самим, чтобы удерживать созданную технику под контролем.
Ведь в будущем новым приёмам случится научиться не только самоуправляемым техникам, но и нам самим, чтобы сдерживать созданную систему под контролем.


В Пока ни один из изобретённых человеком протезов не может полностью заменить руку. Это особенно очевидно, когда необходимо совершить сложную манипуляцию — завязать шнурки, почистить картошку, достать карточку из кошелька.
В Пока ни один из изобретённых индивидом протезов не может полностью перемениться ручку. Это особенно бесспорное, когда необходимо сделать непростую манипуляцию — завязывать шнурки, почистить картошку, достать карту из кошелька.


Фёдор Михайлович Достоевский родился 11 ноября 1821 года в Москве, в дворянской семье. В 16 лет Фёдор с братом переезжает в Петербург и поступает в военно-инженерное училище.
Фёдор Михайлович Достоевский родился 11 ноября 1821 годика в Москве, в дворянской семье. В 16 годиков Фёдор с приятелем перебирается в Санкт-петербург и творит в воинское - инженерное училище.


Идеалом ума, рассматривающего действительность, есть простота, полная ясность, полное понимание. Хорошо известно, что до тех пор, пока вы предмет не постигли, он для вас представляется сложным и туманным.
Идеалом разума, рассматривающего реальность, пребывать простота, упитанная ясность, упитанное понимание. Хорошо известно, что до тех пор, пока вы объект не поняли, он для вас корчит непростым и расплывчатым.


Первый нобелевский лауреат из России, выдающийся учёный, гордость отечественной науки и «первый физиолог мира», как назвали его коллеги на одном из международных съездов.
Первый нобелевский лауреат из России, видный учёный, гордыня отечественной науки и «первый физиолог лада», как охарактеризовали его коллеги на одном из межгосударственных форумов.


Радиоактивный камень, бетон и кирпич, из которых сделаны наши дома (70), но это ерунда! От калия в нашем собственном теле мы ежедневно получаем дозу ещё в шесть раз больше (390).
Радиоактивный камешек, бетон и брикет, из которых сделаны наши дома (70), но это чушь! От калия в нашем собственном туловище мы ежедневно испытываем дозу ещё в шесть раз больше (390).


Но учёбой он интересуется мало, а больше читает книги зарубежных и русских авторов. В 1844 году Фёдор Михайлович Достоевский начинает свою литературную деятельность: выходит его роман «Бедные люди».
Но учёбой он заинтересовывается мало, а больше прочитывает книжки заграничных и русских авторов. В 1844 годике Фёдор Михайлович Достоевский начинает свою литературную работу: получается его роман «Бедные индивиды».


Рекламирует свою продукцию, наведывается к потенциальным заказчикам. Словом, работает не покладая рук. Вот-вот, кажется, и покупателей не останется — ведь жалюзи служат долго. За то и любимы в народе.
Рекламирует свою продукцию, проведывает к потенциальным заказчикам. Высказыванием, действует не покладая ручек. Вот - вот, кажется, и покупателей не уцелеет — ведь жалюзи служат долго. За то и любимы в народе.


Однако возникает достаточно много вопросов и проблем, связанных с применением меметики и её дальнейшим оформлением в науку. Первая — проблема измерения.
Однако появляется достаточно много вопросиков и заморочек, связанных с применением меметики и её дальнейшим оформлением в науку. Первая — заморочка измерения.


Но конечная цель проекта художника кажется не столько практической, сколько концептуальной: Брайдл исследует, что происходит, когда в общество внедряются потенциально опасные или разрушительные технологии.
Но окончательная цель плана живописца кажется не столько практической, сколько концептуальной: Брайдл обследует, что творится, когда в сообщество внедряются потенциально небезопасные или губительные технологии.


Ежегодно в мире проводят более миллиона ампутаций. Самая частая причина — диабет и сосудистые заболевания, а также травмы. В России в протезах рук и ног нуждается около 200 тысяч человек.
Ежегодно в ладе устраивают более миллиона ампутаций. Самая густая причина — диабет и сосудистые недомогания, а также травмы. В России в протезах ручек и ножек бедствует около 200 тысяч индивид.


Рано или поздно, осознанно либо на инстинктивном уровне человек стремится к созданию семьи. Слово «инстинкт» здесь означает биологическую обусловленность потребности в сохранении и увеличении популяции.
Рано или поздно, осознанно либо на инстинктивном уровне индивид направляется к созданию семьи. Высказывание «инстинкт» здесь значит биологическую зависимость нужды в сохранении и увеличении популяции.


Например, радиоизотопы, которые стреляют альфа- и бета-излучением, не могут пробить даже наружный слой кожи или пару сантиметров воздуха.
Например, радиоизотопы, которые обстреливают альфа - и бета - излучением, не могут пробить даже внешний слой кожуры или пару сантиметров воздуха.


По его словам, у протезов есть свои плюсы: например, не мёрзнут руки на морозе, и можно взять горячую кастрюлю и чайник, не опасаясь обжечься.
По его высказываниям, у протезов пребывать свои плюсы: например, не мёрзнут ручки на морозе, и можно захватить пылкую кастрюлю и чайник, не опасаясь обжечься.


– Она практически заглохла, а вернулись лишь немногие люди пожилого возраста, которые уже не могут создавать ВВП или участвовать в конкуренции за интеллектуальное лидерство.
– Она практически заглохла, а вернулись лишь немногие индивиды пожилого возраста, которые уже не могут созидать ВВП или участвовать в конкуренции за разумное лидерство.


По этому показателю оценивается уровень университетов. И вот отечественные ректоры заинтересованы в том, чтобы отправить студентов и аспирантов за границу, но нет никаких гарантий, что те вернутся домой.
По этому показателю оценивается уровень университетов. И вот отечественные ректоры заинтересованы в том, чтобы послать студентов и аспирантов за грань, но нет никаких гарантий, что те вернутся домой.


Люди привыкают транслировать каждый свой чих, как будто это прибавляет им общественного веса или как будто они сомневаются в том, существуют ли они на самом деле.
Индивиды осваиваются транслировать каждый свой чих, как будто это складывается им социального авторитета или как будто они сомневаются в том, имеются ли они на самом занятии.


Маршрут задаётся через планшет. Поехали! 00:01:00 Смотрите, как ловко обходит препятствия. Пешеходы на нерегулируемом переходе, как раз тут срабатывают датчики дальнего действия.
Путь озадачивает через планшет. Махнули! 00: 01: 00 Просматриваете, как ловко исходит препятствия. Пешеходы на нерегулируемом проходе, как раз тут изготовляют указатели далёкого действия.


«Хорошие» мемы — это такие, которые обладают высокой выживаемостью в культурной среде, то есть привлекательны для людей, которые с готовностью копируют их на протяжении многих поколений.
«Положительные» мемы — это такие, которые имеются тонкой выживаемостью в культурной среде, то пребывать привлекательны для индивидов, которые с готовностью копируют их на протяжении многих поколений.


Объяснение простое: население там большое, а образовательный уровень граждан в целом довольно высок и продолжает расти, то есть уехавших есть, кем заменить.
Пояснение бесхитростное: население там значительное, а образовательный уровень граждан в целом довольно тонкий и продолжает подрастать, то пребывать уехавших пребывать, кем перемениться.


Но писателя не казнят, а смертную казнь в последнюю минуту заменяют Сибирской каторгой в Омске.
Но писателя не казнят, а смертельную казнь в конечную минутку меняют Сибирской каторгой в Омске.


Меня утешает вот что: где есть зависимость, там есть и боль. Не всякий человек может пребывать всё время на открытом солнцепёке, лишённый тени одиночества.
Меня утешает вот что: где пребывать зависимость, там пребывать и муку. Не всякий индивид может состоять всё время на явном солнцепёке, лишённый тени одиночества.


Эти сюжеты известны ещё с античности и связаны с природой человека, но интернет придал им размах, а современные психологи возвели в доблесть.
Эти сюжеты знакомые ещё с античности и связаны с природой индивида, но интернет придал им размах, а нынешние психологи построили в доблесть.


Искусство по природе своей мистериально — обращено к глубинам человеческой психики, и поэтому сила его воздействия неисчерпаема, как неисчерпаемы смыслы метафор и образов, средствами которых оно выражает себя.
Мастерство по природе своей мистериально — обращено к глубинам человечной психологии, и поэтому сила его влияния неиссякаемая, как неиссякаемые смыслы метафор и обликов, орудиями которых оно выражает себя.


По оценкам менеджеров «Промы», такая ситуация абсолютно нереальна, так как потенциал рынка жалюзи в России едва ли не в тысячу раз превышает нынешний ежемесячный объём их продаж.
По отметкам менеджеров «Промы», такая обстановка абсолютно ирреальная, так как потенциал базара жалюзи в России едва ли не в тысячу раз превосходит настоящий ежемесячный объём их продаж.


Основные покупатели таких машин — предприятия и промышленное производство. Как можно решить проблему? Помочь беспилотным автомобилям более безопасно ориентироваться в наших городах смогут краудсорсинговые карты.
Главные покупатели таких техник — начинания и индустриальное производство. Как можно вынести заморочку? Помочь беспилотным автомобилям более безопасно разбираться в наших городках сумеют краудсорсинговые карточки.


Молчат о своих страстях, страхах и о своих надеждах, смешных и прекрасных. Молчат о стыде, неуверенности, об унижениях, о болезнях. Они хвастают пороками, часто преувеличенными.
Молчат о своих страстях, страхах и о своих надеждах, смешных и божественных. Молчат о позоре, неуверенности, об унижениях, о патологиях. Они хвастаются пороками, часто преувеличенными.


Первое, самое общее свойство, качество ума — это постоянное сосредоточение мысли на определённом вопросе, предмете. С предметом, в области которого вы работаете, вы не должны расставаться ни на минуту.
Первое, самое единое качество, свойство разума — это постоянное сосредоточение думы на определённом вопросике, объекте. С объектом, в арене которого вы действуете, вы не должны расставаться ни на минутку.


Взяв древнегреческое слово «μιμητής» («миметес»), что означает «подражатель, имитатор», Докинз для удобства отсёк первый слог от его производного «мимем» и получил слово «мем».
Взяв древнегреческое высказывание «μιμητής» («миметес»), что значит «подражатель, имитатор», Докинз для удобства отсёк первый стиль от его производного «мимем» и получил высказывание «мем».


Павлова называли «романтической, почти легендарной личностью», «гражданином мира», а друг учёного, писатель Герберт Уэллс, сказал о нём: «Это звезда, которая освещает мир, проливая свет на ещё не изведанные пути».
Павлова характеризовали «романтической, почти легендарной личностью», «гражданином лада», а кореш учёного, писатель Герберт Уэллс, сказал о нём: «Это звезда, которая описывает лад, проливая свет на ещё не изведанные маршруте».


Пока беспилотные машины существуют в бета-версии, исследователи работают над системами, способными анализировать дорогу лучше, чем водитель-человек.
Пока беспилотные техники имеются в бета - версии, исследователи действуют над привычками, способными анализировать трассу лучше, чем водитель - индивид.


Славный парень, недавно уволенный с ТВ, спешит сообщить, что он на Лазурном Берегу, и вывесить фотографию откупоренной бутылки шампанского. 70 лайков за 15 минут! 300 за час!
Славный юноша, недавно уволенный с ТЕЛЕВИДЕНИЕ, торопится доносить, что он на Лазурном Берегу, и повесить фотографию откупоренной бутылки шампанского. 70 лайков за 15 минуток! 300 за час!


Почему машины не готовы принимать «разумные» решения? Ещё одна нерешённая проблема заключается в создании системы, которая может принимать разумные решения — регулировать скорость и менять полосы движения.
Почему техники не готовы зачислять «благоразумные» решения? Ещё одна нерешённая заморочка заключается в создании привычки, которая может зачислять благоразумные решения — налаживать скорость и обменивать ленты сообщения.


Уже к середине следующего года глава компании собирается выпустить на дороги США более миллиона полностью беспилотных машин. Понятие «автопилот» компания Tesla начала использовать для своих электромобилей ещё в 2015 году.

In [16]:
stats_df = pd.DataFrame()

stats_df['Список слов для замены'] = LIST_WORDS_TO_REPLACE
stats_df['Количество слов для замены'] = LEN_WORDS_TO_REPLACE
stats_df['Найденные синонимы для каждого слова'] = FOUNDED_SYNONYMS
stats_df['Количество найденных синонимов для каждого слова'] = SYNONYMS_COUNT
stats_df['Отсортированные по уменьшению уровня сложности синонимы для каждого слова'] = RANKED_SYNONYMS
stats_df['Выбранный синоним для каждого слова'] = CHANGED_SYNONYM

stats_df

,Список слов для замены,Количество слов для замены,Найденные синонимы для каждого слова,Количество найденных синонимов для каждого слова,Отсортированные по уменьшению уровня сложности синонимы для каждого слова,Выбранный синоним для каждого слова
0,"(радиация, незаразна, мощными, дозами, излучен...",11,"[[радиоизлучение], [], [могучий, мощнейший, мо...","[1, 0, 4, 0, 1, 0, 1, 0, 1, 12, 16]","[[], [], [могучий], [], [], [], [], [], [], []...","[могучими, индивидов]"
1,"(компания, объявила, инвестиции, миллиарда, до...",15,"[[компашка, фирма], [объявлять, объявлять, огл...","[2, 4, 3, 0, 4, 0, 11, 1, 1, 2, 22, 3, 5, 0, 14]","[[фирма], [объявлять, объявлять], [], [], [], ...","[фирма, , привычку, фирма, , собственников, те..."
2,"(Множество, повестей, Двойник, Дядюшкин, сон, ...",15,"[[куча, масса, тьма, уйма], [], [], [], [греза...","[4, 0, 0, 0, 3, 1, 3, 4, 0, 0, 3, 36, 1, 2, 1]","[[куча, масса, тьма], [], [], [], [], [], [под...","[, , , , пребывали, выдающегося]"
3,"(Встречи, одноклассников, одногруппников, прев...",15,"[[турнир, соревнование, первенство, баталия], ...","[4, 1, 0, 10, 1, 0, 19, 10, 4, 17, 0, 4, 15, 7...","[[турнир, первенство, соревнование], [], [], [...","[, преображаются, пирушки, разрываются, доноси..."
4,"(Самопрезентация, главная, черта, времени, неи...",19,"[[], [основной, наиглавнейший, главнейший], [г...","[0, 3, 13, 6, 3, 9, 16, 10, 19, 1, 2, 8, 8, 7,...","[[], [основной], [рубеж, грань, предел, линия,...","[основная, грань, , неисправимая, патология, И..."
...,...,...,...,...,...,...
115,"(испытания, участников, Жюри, определит, автом...",14,"[[крест, экзамен, проверка], [участница], [], ...","[3, 1, 0, 32, 6, 4, 0, 22, 16, 10, 0, 2, 10, 5]","[[крест, экзамен], [участница], [], [помещать,...","[, , задаст, , видится, индивидов, отвечает, д..."
116,"(Прома, способна, предложить, дилерам, божески...",16,"[[], [], [предлагать, предлагать, внести, внос...","[0, 0, 13, 0, 1, 3, 0, 5, 2, 1, 11, 4, 0, 7, 1...","[[], [], [выдвигать, вносить, предлагать, пред...","[, подходящие, платы, продолжительном, привычк..."
117,"(единственный, игрок, рынке, большинство, круп...",12,"[[единый], [], [базарчик, базар, рыночек, рыно...","[1, 0, 4, 0, 9, 3, 13, 17, 0, 6, 13, 2]","[[единый], [], [базар], [], [внушительный, пор...","[единый, базаре, внушительных, намереваются, ,..."
118,"(крупнейших, стран, поставщиков, высококлассно...",15,"[[порядочный, внушительный, изрядный, широкий,...","[9, 3, 0, 2, 0, 1, 6, 4, 1, 1, 0, 1, 0, 0, 5]","[[внушительный, порядочный, широкий], [держава...","[порядочнейших, держав, первоклассной, межгосу..."
119,"(велик, подвиг, жечь, виртуальных, кострах, не...",9,"[[значительный, приличный, немалый, больший, м...","[8, 0, 21, 0, 0, 0, 0, 1, 19]","[[значительный, приличный, больший, многочисле...","[значительный, сжигать, занятию]"

In [17]:
stats_df.to_csv('synonyms_stats.csv')

In [18]:
len(augmented_texts)

119

In [14]:
aug_df = pd.DataFrame()
aug_df['text'] = texts
aug_df['augmented-text'] = augmented_texts
aug_df

,text,augmented-text
0,"3:38–3:54 Собственно, сама по себе радиация не...","3: 38 – 3: 54 Собственно, сама по себе радиаци..."
1,Недавно компания Uber объявила об инвестиции о...,Недавно фирма Uber объявила об инвестиции одно...
2,"Множество повестей: «Двойник», «Дядюшкин сон»,...","Множество повестей: «Двойник», «Дядюшкин сон»,..."
3,Встречи одноклассников и одногруппников превра...,Встречи одноклассников и одногруппников преобр...
4,Самопрезентация — как главная черта времени и ...,Самопрезентация — как основная грань времени и...
...,...,...
114,00:00:24 А сегодня испытания. 13 участников. Ж...,00: 00: 24 А сегодня испытания. 13 участников....
115,«Прома» способна предложить дилерам вполне бож...,«Прома» способна предложить дилерам вполне под...
116,Tesla — не единственный игрок на рынке: больши...,Tesla — не единый игрок на базаре: большинство...
117,"Понятно, что среди крупнейших стран – поставщи...","Понятно, что среди порядочнейших держав – пост..."
118,"Он велик, этот подвиг: жечь себя живьём на вир...","Он значительный, этот подвиг: сжигать себя жив..."

In [15]:
aug_df.to_csv('c2_augmented_synonyms.csv')